### PR TITLE
Support for HAML templates

### PR DESCRIPTION
**Pull request by adampope**
http://haml.info

### CODE REVIEW

**Comment by gorriecoe** [comment]
Hi Adam,  I'm happy to merge this.  I would also like to add a snippet to components.cson but I'm not completely familiar with Haml.  Are you able to confirm the snippet below is correct?  If its not, are you able to correct and add it to the PR?

```
...
".text.haml":
  'Fontawesome Icon Haml':
    'prefix': 'fa'
    'body': "%i.fa${1}{\"aria-hidden\" => \"true\"}${0}"
```

**Comment by adampope** [comment]
You were missing a `.`, I've added it to the PR :)

**Comment by gorriecoe** [comment]
Thanks Adam =)

**Comment by gorriecoe** [comment]
Now published to 0.2.0

**Pull request merged**
